blog/urls.py
from django.urls import path
from .views import BlogListView, BlogCreateView, blogDetailView, blogUpdateView, blogDeleteView
app_name="blog"

urlpatterns = [
    path('', BlogListView.as_view(),name="home"),
    path('create/', BlogCreateView.as_view(), name='create'),
    path('<int:pk>/', blogDetailView.as_view(),name='detail'),
    path('<int:pk>/update/', blogUpdateView.as_view(),name='update'),
    path('<int:pk>/delete/', blogDeleteView.as_view(),name='delete'),
]   

core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name="home"),

    path('blog/',include('blog.urls',namespace='blog'))
]

blog/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=250)
    content = models.TextField()

blog/forms.py
from django import forms 
from .models import Post


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title','content')

blog/views.py
from re import template
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import View, UpdateView, DeleteView
from .models import Post
from django.urls import reverse_lazy



from .forms import PostCreateForm

# Create your views here.


class BlogListView(View):
    def get(self, request, *args, **kargs):
        posts = Post.objects.all()
        context = {
            'posts': posts
        }
        return render(request,'blog_list.html',context)


class BlogCreateView(View):
    def get(self, request, *args, **kargs):
        form= PostCreateForm()
        context = {
            'form': form
        }
                
        return render(request, "blog_create.html", context)

    def post(self, request, *args, **kargs):
        if request.method=="POST":
            form= PostCreateForm(request.POST)
            if form.is_valid():
                title = form.cleaned_data.get('title')
                content = form.cleaned_data.get('content')

                p, created = Post.objects.get_or_create(title=title,content=content)

                p.save()
            
                return redirect('blog:home')



        context = {
        
        }
                
        return render(request, "blog_create.html", context)

 


class blogDetailView(View):
    def get(self, request, pk, *args, **kwars):
        post = get_object_or_404(Post, pk=pk)
        context={
            'post': post
        }
        return render(request, 'blog_detail.html', context)


class blogUpdateView(UpdateView):
    model=Post
    fields=['title','content']
    template_name='blog_update.html'

    def get_success_url(self):
        pk = self.kwargs['pk']
        return reverse_lazy('blog:detail', kargs={'pk':pk})

class blogDeleteView(DeleteView):
    model=Post
    template_name='blog_delete.html'
    success_url= reverse_lazy('blog:home')

core/views.py
from django.views.generic import View
from django.shortcuts import render

class HomeView(View):
    def get(self, request, *args, **kargs):
        context={


        }
        
        return render(request, "index.html",context)

templates/base.html
{% load tailwind_tags %}
<html lang="en">
<head>
    
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% tailwind_css %}
    <title>Document</title>

</head>
<body>
    
    {% block content %}{% endblock content %}

</body>
</html>

templates/blog_create.html
{% extends 'base.html' %}

{% block content %}

<form method="POST">


    {% csrf_token %}
<div style="padding-left: 26px;" >
    title{{form.title}}
</div>
    <br>
<div>
    content{{form.content}}
    <button type="submit" class="text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700">Submit</button>
    
    </form>
</div> 
{% endblock content %}

templates/blog_delete.html
Are you sure? :0
<form method="POST">

    {% csrf_token %}
   {{form}}
    <button type="submit">Delete</button>
    </form>

templates/blog_detail.html
{{post.title}}
<br>
{{post.content}}

templates/blog_list.html
{% extends 'base.html' %}

{% block content %}

<h1 class="underline text-2xl">blog list</h1>

<br>

{% for post in posts %}
<div>
<a style="margin-top: 20px;" class="text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700" href="{% url 'blog:detail' post.id %}">{{post.title}}</a>
</div>
<br>
<div>
<a class="text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700" href="{% url 'blog:update' post.id %}">Update</a>
</div>
<br>
<div>
<a class="text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700" href="{% url 'blog:delete' post.id %}">Delete</a>
</div>
{% endfor %}
<br>

<a class="text-gray-900 bg-white border border-gray-300 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-200 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-gray-800 dark:text-white dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700" href="{% url 'blog:create' %}">Create</a>

{% endblock content %}

templates/blog_update.html
<form method="POST">

    {% csrf_token %}
    title{{form.title}}
    <br>
    content{{form.content}}
    <button type="submit">update</button>
    </form>

templates/index.html
{% extends 'base.html' %}

{% block content %}

<a> hola, visita el  <a href="{% url 'blog:home' %}">blog aqui</a>

{% endblock content %}

theme/templates/base.html
{% load static tailwind_tags %}
<!DOCTYPE html>
<html lang="en">
	<head>
    <title>Django Tailwind</title>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<meta http-equiv="X-UA-Compatible" content="ie=edge">
		{% tailwind_css %}
	</head>

	<body class="bg-gray-50 font-serif leading-normal tracking-normal">
		<div class="container mx-auto">
			<section class="flex items-center justify-center h-screen">
				<h1 class="text-5xl">Django + Tailwind = ❤️</h1>
			</section>
		</div>
	</body>
</html>